// One-click test page (Examples → "Test page"): a short physics text whose
// equations are inserted PROGRAMMATICALLY through performInsert() with explicit
// settings, so every option of the add-in gets exercised in one go. Pure data,
// so the equations are render-tested like the examples.
//
// Block shapes:
//   { h1 } / { h2 } / { p }            — a heading or a prose paragraph
//   { before?, eq, after? }             — prose, then an equation inserted at the
//                                         end of that paragraph, then more prose
//                                         after the picture (inline equations);
//                                         display equations get their own
//                                         paragraph (before/after omitted).
// eq = { latex, displayMode, font, sizeMode, fixedPt, color, numbered, style };
// missing keys fall back to the runner's defaults (display · Termes · match body
// · black · unnumbered).
import { findExample } from './examples.js';

const NS = findExample('navierstokes');

export const TEST_PAGE = [
  { h1: 'Recorde test page' },
  { p: 'Generated by the add-in. Every equation below was inserted programmatically with the settings shown in brackets, so this page exercises modes, fonts, sizes, colour, the macro preamble and all numbering styles. The checks in section 6 are manual.' },

  { h2: '1. Inline equations in running text' },
  { before: 'Consider a particle of mass m in a potential V(x). Its energy is conserved, ',
    eq: { latex: String.raw`E = \frac{p^2}{2m} + V(x)`, displayMode: 'inline', font: 'termes', sizeMode: 'body' },
    after: ' [inline · Termes · match body], so the motion stays on a level set of E. The baseline of the equation should sit on the text line.' },
  { before: 'For a harmonic well the frequency follows from the curvature at the minimum, ',
    eq: { latex: String.raw`\omega = \sqrt{V''(x_0)/m}`, displayMode: 'inline', font: 'newcm', sizeMode: 'body' },
    after: ' [inline · New Computer Modern · match body].' },
  { before: 'The imaginary unit and Euler’s number come from the document preamble: ',
    eq: { latex: String.raw`\E^{\I\pi} + 1 = 0`, displayMode: 'inline', font: 'termes', sizeMode: 'fixed', fixedPt: 14, color: '#8b0000' },
    after: ' [inline · fixed 14 pt · dark red].' },

  { h2: '2. Display equation, unnumbered' },
  { p: 'The free-particle propagator in one dimension [display · STIX Two · match body]; it must be centred on its own paragraph while this prose stays left-aligned:' },
  { eq: { latex: String.raw`K(x_f,t_f;x_i,t_i) = \sqrt{\frac{m}{2\pi\I\hbar\,(t_f-t_i)}}\;\exp\!\left[\frac{\I m (x_f-x_i)^2}{2\hbar (t_f-t_i)}\right]`,
          displayMode: 'display', font: 'stix2', sizeMode: 'body' } },

  { h2: '3. Numbering — inline style' },
  { p: 'Two numbered equations in the inline style: the number trails the equation inside the picture [display · numbered · inline style · Termes, then Pagella].' },
  { eq: { latex: String.raw`\int_{-\infty}^{\infty} e^{-x^2}\,dx = \sqrt{\pi}`, displayMode: 'display', font: 'termes', numbered: true, style: 'inline' } },
  { eq: { latex: String.raw`x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}`, displayMode: 'display', font: 'pagella', numbered: true, style: 'inline' } },

  { h2: '4. Numbering — flush-right table style' },
  { p: 'Each equation sits in a borderless row, centred, with its number at the right margin as Word text [display · numbered · table style · Termes, then Asana Math].' },
  { eq: { latex: String.raw`\VNabla \cdot \vb{E} = \frac{\rho}{\varepsilon_0}`, displayMode: 'display', font: 'termes', numbered: true, style: 'table' } },
  { eq: { latex: String.raw`\HOp{H}\,\ket{\psi} = E\,\ket{\psi}`, displayMode: 'display', font: 'asana', numbered: true, style: 'table' } },

  { h2: '5. Numbering — Word field style' },
  { p: 'The number is a native SEQ field (Alt+F9 shows { SEQ equation \\* ARABIC }). Desktop only: on Word on the web these two fall back to the inline style [display · numbered · field style].' },
  { eq: { latex: String.raw`\Avg*{\HOp{H}} = \sum_n \Abs{c_n}^2 E_n`, displayMode: 'display', font: 'termes', numbered: true, style: 'field' } },
  { eq: { latex: String.raw`\OpComm{\HOp{x}, \HOp{p}} = \I\hbar`, displayMode: 'display', font: 'tex', numbered: true, style: 'field' } },

  { h2: '6. From the examples picker' },
  { p: 'The Navier–Stokes example, numbered in the current document style [display · numbered · document style].' },
  { eq: { latex: NS.latex, displayMode: 'display', font: 'termes', numbered: true } },

  { h2: '7. Manual checks' },
  { p: 'a) Click the Gaussian integral in section 3: the pane loads it, the status says “Editing”, the preview shows its number. Change the integrand to e^{-x²/2} and press Ctrl+Enter: it updates in place and keeps its number.' },
  { p: 'b) Delete the quadratic-formula paragraph in section 3, then click “Renumber all”: the later equations close the gap, field equations included (Ctrl+A, F9 must agree).' },
  { p: 'c) Open “Equations in this document” in the pane: entries in document order with their numbers; click the last one — Word jumps to it and the pane loads it.' },
  { p: 'd) With an equation loaded, press Esc in the editor: the pane returns to “New equation” without touching the document.' },
  { p: 'e) Type \\frac{a}{ in the editor: “Missing close brace” appears in red under the source; complete it and the message disappears.' },
  { p: 'f) File → Account → Office Theme → Dark Gray: the pane turns dark, the preview stays white, dropdowns match the pane. Back to Colorful.' },
];

export function testPageEquations() {
  return TEST_PAGE.filter((b) => b.eq).map((b) => b.eq);
}
